### ISSUE TITLE
Add the code!

### ISSUE THREAD

**Issue by ntoll** [g--o/CuteDE#1]
Hi,

This could be a really interesting example project... but I notice that the `CuteLauncher` and `CuteWM` directories (presumably containing Python code) are not browsable. Care to fix that..?

Thank you in advance!

N.

**Comment by g--o** [comment]
Hi, this repo is made so that when you run the install script it clones it.

Projects are browsable here:
https://github.com/g--o/CuteLauncher
https://github.com/g--o/CuteWM

Why not git-init-recursive? Simply because CuteLauncher and CuteWM should be independent but CuteDE should configure them to work together.
Could make branches but I'd rather have this way so I ensure both projects are configurable enough, rather than having to customize in a branch.

Thanks for checking it out!
One thing to note is that CuteLauncher is indev right now so as I'm working on it after it clones you might want to checkout CuteLauncher to an older version, so if you encounter any problem just post right here and I'll gladly help :)

**Comment by g--o** [comment]
@ntoll 
Do you need any further help or can I close the issue?

**Comment by ntoll** [comment]
Sorry... I should have responded. Your answer solved it. Thank you.
